
targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/providers/**
      - lib/api/types/**
      - lib/dto/**
      - pubspec.yaml
    builders:
      json_serializable:
        options: {}
      riverpod_generator:
        options: {}
      freezed:
        options: {}
      fairy_forum_admin_app:version_builder:
        enabled: true

builders:
  version_builder:
    import: "package:fairy_forum_admin_app/builders/version_builder.dart"
    builder_factories: ["versionBuilder"]
    build_extensions: {"$lib$": ["version.g.dart"]}
    auto_apply: dependents
    build_to: source
